// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TestUser
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testUserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TestUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		age("age"),
		phone("phone"),
		mail("mail"),
		sheng("sheng"),
		shi("shi"),
		qu("qu");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testUserMendixObject)
	{
		if (testUserMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testUserMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testUserMendixObject = testUserMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestUser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.TestUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.TestUser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.TestUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TestUser(context, mendixObject);
	}

	public static myfirstmodule.proxies.TestUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TestUser.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.TestUser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.TestUser.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of age
	 */
	public final java.lang.String getage()
	{
		return getage(getContext());
	}

	/**
	 * @param context
	 * @return value of age
	 */
	public final java.lang.String getage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.age.toString());
	}

	/**
	 * Set value of age
	 * @param age
	 */
	public final void setage(java.lang.String age)
	{
		setage(getContext(), age);
	}

	/**
	 * Set value of age
	 * @param context
	 * @param age
	 */
	public final void setage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String age)
	{
		getMendixObject().setValue(context, MemberNames.age.toString(), age);
	}

	/**
	 * @return value of phone
	 */
	public final java.lang.String getphone()
	{
		return getphone(getContext());
	}

	/**
	 * @param context
	 * @return value of phone
	 */
	public final java.lang.String getphone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.phone.toString());
	}

	/**
	 * Set value of phone
	 * @param phone
	 */
	public final void setphone(java.lang.String phone)
	{
		setphone(getContext(), phone);
	}

	/**
	 * Set value of phone
	 * @param context
	 * @param phone
	 */
	public final void setphone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.phone.toString(), phone);
	}

	/**
	 * @return value of mail
	 */
	public final java.lang.String getmail()
	{
		return getmail(getContext());
	}

	/**
	 * @param context
	 * @return value of mail
	 */
	public final java.lang.String getmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.mail.toString());
	}

	/**
	 * Set value of mail
	 * @param mail
	 */
	public final void setmail(java.lang.String mail)
	{
		setmail(getContext(), mail);
	}

	/**
	 * Set value of mail
	 * @param context
	 * @param mail
	 */
	public final void setmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mail)
	{
		getMendixObject().setValue(context, MemberNames.mail.toString(), mail);
	}

	/**
	 * @return value of sheng
	 */
	public final java.lang.String getsheng()
	{
		return getsheng(getContext());
	}

	/**
	 * @param context
	 * @return value of sheng
	 */
	public final java.lang.String getsheng(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sheng.toString());
	}

	/**
	 * Set value of sheng
	 * @param sheng
	 */
	public final void setsheng(java.lang.String sheng)
	{
		setsheng(getContext(), sheng);
	}

	/**
	 * Set value of sheng
	 * @param context
	 * @param sheng
	 */
	public final void setsheng(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sheng)
	{
		getMendixObject().setValue(context, MemberNames.sheng.toString(), sheng);
	}

	/**
	 * @return value of shi
	 */
	public final java.lang.String getshi()
	{
		return getshi(getContext());
	}

	/**
	 * @param context
	 * @return value of shi
	 */
	public final java.lang.String getshi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.shi.toString());
	}

	/**
	 * Set value of shi
	 * @param shi
	 */
	public final void setshi(java.lang.String shi)
	{
		setshi(getContext(), shi);
	}

	/**
	 * Set value of shi
	 * @param context
	 * @param shi
	 */
	public final void setshi(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shi)
	{
		getMendixObject().setValue(context, MemberNames.shi.toString(), shi);
	}

	/**
	 * @return value of qu
	 */
	public final java.lang.String getqu()
	{
		return getqu(getContext());
	}

	/**
	 * @param context
	 * @return value of qu
	 */
	public final java.lang.String getqu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.qu.toString());
	}

	/**
	 * Set value of qu
	 * @param qu
	 */
	public final void setqu(java.lang.String qu)
	{
		setqu(getContext(), qu);
	}

	/**
	 * Set value of qu
	 * @param context
	 * @param qu
	 */
	public final void setqu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qu)
	{
		getMendixObject().setValue(context, MemberNames.qu.toString(), qu);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testUserMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TestUser that = (myfirstmodule.proxies.TestUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
