// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.ArrayList;
import java.util.List;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import org.apache.log4j.PropertyConfigurator;
import com.alibaba.excel.*;
import myfirstmodule.MyTestUser;
import myfirstmodule.FreezeAndFilter;
import myfirstmodule.proxies.TestUser;

public class EasyExcel extends CustomJavaAction<java.lang.String>
{
	private java.lang.String File_Name;
	private java.lang.String HOST_ADRESS;
	private java.util.List<IMendixObject> __UserList;
	private java.util.List<myfirstmodule.proxies.TestUser> UserList;

	public EasyExcel(IContext context, java.lang.String File_Name, java.lang.String HOST_ADRESS, java.util.List<IMendixObject> UserList)
	{
		super(context);
		this.File_Name = File_Name;
		this.HOST_ADRESS = HOST_ADRESS;
		this.__UserList = UserList;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.UserList = java.util.Optional.ofNullable(this.__UserList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__UserListElement -> myfirstmodule.proxies.TestUser.initialize(getContext(), __UserListElement))
			.collect(java.util.stream.Collectors.toList());

		// BEGIN USER CODE
		FileInputStream fileInputStream = null;
		try {
			Properties properties = new Properties();
			fileInputStream = new FileInputStream(System.getProperty("user.dir")+"/log4j.properties");
			properties.load(fileInputStream);
			PropertyConfigurator.configure(properties);

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (fileInputStream != null) {
				try {
					fileInputStream.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

		String filename=File_Name+".xlsx";
		String strr= System.getProperty("user.dir")+"\\web\\"+filename;

		List<myfirstmodule.MyTestUser> a = new ArrayList<>();
		String restr="";
		for (TestUser q:this.UserList) {
			MyTestUser myuser=new MyTestUser();
			myuser.setName(q.getname());
			myuser.setAge(q.getage());
			myuser.setPhone(q.getphone());
			myuser.setMail(q.getmail());
			myuser.setSheng(q.getsheng());
			myuser.setShi(q.getshi());
			myuser.setQu(q.getqu());
			a.add(myuser);
		}
		com.alibaba.excel.EasyExcel.write(strr,myfirstmodule.MyTestUser.class)
				.sheet("sheet1")
				.registerWriteHandler(new FreezeAndFilter())
				.doWrite(() -> {
					return a;
				});


		return HOST_ADRESS+"/"+filename;


















		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EasyExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
